// MongoDB schema
const userData = require("../models/UserData");

// Class { FetchUserData } to fetch user data using either { email } or by { _id } generated by MongoDB during creation
class FetchUserData {
  // Asynchronous function to fetch data using { email } in database from user's request
  async fetchUserByEmail({ email }) {
    const result = await userData
      .find({
        email: email,
      })
      .then((results) => results)
      .catch((err) => err);
    return result;
  }

  // Asynchronous function to fetch data using { _id } in database from JWT token
  async fetchUserById({ id }) {
    const result = await userData
      .find({ _id: id })
      .then((results) => results)
      .catch((err) => err);
    return result;
  }
}

// Class Object
const fetchUserObject = new FetchUserData();
module.exports = fetchUserObject;
